# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import swiftwind.settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20190601_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='additional_currencies',
            field=swiftwind.settings.models.ChoiceArrayField(base_field=models.CharField(choices=[('BYN', 'Belarussian Ruble'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default=[], max_length=3), blank=True, default=[], size=None),
        ),
    ]
